[package]
name = "rorth"
version = "0.1.0"
edition = "2021"
default-run = "rorth"

[[bin]]
name = "rorth"
path = "src/main.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[dependencies]
static_assertions = "1.1.0"
strum = "0.26"
strum_macros = "0.26"
